// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbObchsWpz_GSyMfk-B-7kmKTqrxtgiKQ',
    appId: '1:750593247386:web:33836e9b7a46557fe0b723',
    messagingSenderId: '750593247386',
    projectId: 'datn-628de',
    authDomain: 'datn-628de.firebaseapp.com',
    databaseURL: 'https://datn-628de-default-rtdb.firebaseio.com',
    storageBucket: 'datn-628de.appspot.com',
    measurementId: 'G-RC88NYPETN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2nCHDw_dY15KiBF_o06s0kSthwJ6MMc',
    appId: '1:750593247386:android:9f6255b4f25c35f1e0b723',
    messagingSenderId: '750593247386',
    projectId: 'datn-628de',
    databaseURL: 'https://datn-628de-default-rtdb.firebaseio.com',
    storageBucket: 'datn-628de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujlc-WLGZ3ZZru8Ef7jT4SPI7ytwbUkc',
    appId: '1:750593247386:ios:746f944a3c8b3c90e0b723',
    messagingSenderId: '750593247386',
    projectId: 'datn-628de',
    databaseURL: 'https://datn-628de-default-rtdb.firebaseio.com',
    storageBucket: 'datn-628de.appspot.com',
    iosBundleId: 'com.example.cakeCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDujlc-WLGZ3ZZru8Ef7jT4SPI7ytwbUkc',
    appId: '1:750593247386:ios:746f944a3c8b3c90e0b723',
    messagingSenderId: '750593247386',
    projectId: 'datn-628de',
    databaseURL: 'https://datn-628de-default-rtdb.firebaseio.com',
    storageBucket: 'datn-628de.appspot.com',
    iosBundleId: 'com.example.cakeCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbObchsWpz_GSyMfk-B-7kmKTqrxtgiKQ',
    appId: '1:750593247386:web:a051d3e40c063961e0b723',
    messagingSenderId: '750593247386',
    projectId: 'datn-628de',
    authDomain: 'datn-628de.firebaseapp.com',
    databaseURL: 'https://datn-628de-default-rtdb.firebaseio.com',
    storageBucket: 'datn-628de.appspot.com',
    measurementId: 'G-NZ6CB60LRX',
  );

}